kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: samplewebapp
  namespace: samplewebapp
spec:
  template: 
    metadata:
    spec:
      containers:
        - name: samplewebapp
          image: "nginxdemos/hello"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
  replicas: 1 
