kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  labels: 
    app: "samplewebapp"
  name: "samplewebapp"
spec:
  selector:
    matchLabels: 
      name: "samplewebapp"
  template: 
    metadata:
      labels:
        name: "samplewebapp"      
        app: "samplewebapp"
    spec:
      containers:
        - name: "samplewebapp"
          image: "hello-world:latest
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
  replicas: 1 
