kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: samplewebapp
  namespace: samplewebapp
spec:
  path: /
  to:
    kind: Service
    name: samplewebapp
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
