apiVersion: v1
kind: Service
metadata:
  name: samplewebapp
  namespace: samplewebapp
  labels:
    name: samplewebapp
    app: samplewebapp
spec:
  type: NodePort
  ports:
  - port: 8080
    name: porta2
    protocol: TCP
    nodePort: 31888
    targetPort: 8080
  selector:
    app:  samplewebapp
